<?php

namespace Database\Seeders;

use App\Models\Settlement;
use App\Models\Umkm;
use Illuminate\Database\Seeder;

class UmkmSeeder extends Seeder
{
    public function run(): void
    {
        // Get settlement IDs
        $settlements = Settlement::all();

        $umkmData = [
            [
                'business_name' => 'Warung Makan Sari Rasa',
                'slug' => 'warung-makan-sari-rasa',
                'owner_name' => 'Ibu Siti Rahayu',
                'category' => 'makanan',
                'description' => 'Menyajikan masakan tradisional Jawa dengan cita rasa autentik dan harga terjangkau.',
                'address' => 'Dusun I RT 02/RW 01',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081234567890',
                'email' => null,
                'website' => null,
                'operating_hours' => '06:00 - 21:00 WIB',
                'products' => 'Nasi gudeg, soto ayam, pecel lele, ayam bakar',
                'services' => 'Dine in, take away, catering',
                'price_range' => 'Rp 10.000 - Rp 25.000',
                'employee_count' => 4,
                'monthly_revenue' => 15000000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=250&fit=crop']),
                'rating' => 4.5,
                'total_reviews' => 23,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(6),
            ],
            [
                'business_name' => 'Kerajinan Bambu Krandegan',
                'slug' => 'kerajinan-bambu-krandegan',
                'owner_name' => 'Bapak Sumarno',
                'category' => 'kerajinan',
                'description' => 'Produksi berbagai kerajinan dari bambu berkualitas tinggi dan ramah lingkungan.',
                'address' => 'Dusun II RT 03/RW 02',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081345678901',
                'email' => null,
                'website' => null,
                'operating_hours' => '08:00 - 17:00 WIB',
                'products' => 'Keranjang bambu, anyaman tikar, furniture bambu, hiasan dinding',
                'services' => 'Custom design, workshop kerajinan',
                'price_range' => 'Rp 25.000 - Rp 500.000',
                'employee_count' => 6,
                'monthly_revenue' => 8500000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=250&fit=crop']),
                'rating' => 5.0,
                'total_reviews' => 18,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(8),
            ],
            [
                'business_name' => 'Tani Organik Sejahtera',
                'slug' => 'tani-organik-sejahtera',
                'owner_name' => 'Bapak Ahmad Fauzi',
                'category' => 'pertanian',
                'description' => 'Kelompok tani yang memproduksi beras organik dan sayuran segar tanpa pestisida.',
                'address' => 'Dusun III RT 01/RW 03',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081456789012',
                'email' => 'organik.sejahtera@gmail.com',
                'website' => null,
                'operating_hours' => '24 Jam (Pre-order)',
                'products' => 'Beras organik, sayuran hijau, cabai, tomat, jagung manis',
                'services' => 'Konsultasi pertanian organik, penyediaan bibit',
                'price_range' => 'Rp 15.000 - Rp 50.000/kg',
                'employee_count' => 12,
                'monthly_revenue' => 22000000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=250&fit=crop']),
                'rating' => 4.2,
                'total_reviews' => 31,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subYear(),
            ],
            [
                'business_name' => 'Service Motor Jaya',
                'slug' => 'service-motor-jaya',
                'owner_name' => 'Bapak Joko Susilo',
                'category' => 'jasa',
                'description' => 'Bengkel motor terpercaya dengan teknisi berpengalaman dan suku cadang original.',
                'address' => 'Dusun I RT 04/RW 01',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081567890123',
                'email' => null,
                'website' => null,
                'operating_hours' => '07:00 - 19:00 WIB',
                'products' => null,
                'services' => 'Service berkala, ganti oli, tune up, perbaikan mesin',
                'price_range' => 'Rp 25.000 - Rp 200.000',
                'employee_count' => 3,
                'monthly_revenue' => 12000000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=400&h=250&fit=crop']),
                'rating' => 4.6,
                'total_reviews' => 42,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(10),
            ],
            [
                'business_name' => 'Konveksi Mandiri',
                'slug' => 'konveksi-mandiri',
                'owner_name' => 'Ibu Rina Kartika',
                'category' => 'tekstil',
                'description' => 'Jasa konveksi pakaian, seragam, dan tas dengan kualitas jahitan terbaik.',
                'address' => 'Dusun II RT 01/RW 02',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081678901234',
                'email' => 'konveksi.mandiri@yahoo.com',
                'website' => null,
                'operating_hours' => '08:00 - 16:00 WIB',
                'products' => 'Seragam sekolah, kaos polo, jaket, tas kain, kemeja',
                'services' => 'Desain custom, sablon, bordir',
                'price_range' => 'Rp 35.000 - Rp 150.000',
                'employee_count' => 8,
                'monthly_revenue' => 18000000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop']),
                'rating' => 4.3,
                'total_reviews' => 27,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(4),
            ],
            [
                'business_name' => 'Kue Tradisional Ibu Yanti',
                'slug' => 'kue-tradisional-ibu-yanti',
                'owner_name' => 'Ibu Yanti Susanti',
                'category' => 'makanan',
                'description' => 'Produksi aneka kue tradisional dan modern untuk acara khusus dan konsumsi harian.',
                'address' => 'Dusun III RT 02/RW 03',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081789012345',
                'email' => null,
                'website' => null,
                'operating_hours' => '05:00 - 20:00 WIB',
                'products' => 'Kue lapis, onde-onde, klepon, kue sus, donat, roti bakar',
                'services' => 'Catering kue, pesanan khusus untuk acara',
                'price_range' => 'Rp 2.000 - Rp 15.000/pcs',
                'employee_count' => 3,
                'monthly_revenue' => 9500000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&h=250&fit=crop']),
                'rating' => 4.9,
                'total_reviews' => 38,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(7),
            ],
            [
                'business_name' => 'Toko Kelontong Berkah',
                'slug' => 'toko-kelontong-berkah',
                'owner_name' => 'Bapak Sutrisno',
                'category' => 'jasa',
                'description' => 'Toko kelontong lengkap dengan berbagai kebutuhan sehari-hari dan pelayanan 24 jam.',
                'address' => 'Dusun I RT 01/RW 01',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081890123456',
                'email' => null,
                'website' => null,
                'operating_hours' => '24 Jam',
                'products' => 'Sembako, minuman, makanan ringan, pulsa, token listrik',
                'services' => 'Delivery, pembayaran tagihan, top up e-wallet',
                'price_range' => 'Rp 500 - Rp 100.000',
                'employee_count' => 2,
                'monthly_revenue' => 14000000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=250&fit=crop']),
                'rating' => 4.4,
                'total_reviews' => 56,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(15),
            ],
            [
                'business_name' => 'Pertukangan Kayu Maju',
                'slug' => 'pertukangan-kayu-maju',
                'owner_name' => 'Bapak Agus Santoso',
                'category' => 'kerajinan',
                'description' => 'Jasa pertukangan kayu dan furniture custom dengan kualitas terjamin.',
                'address' => 'Dusun II RT 04/RW 02',
                'settlement_id' => $settlements->random()->id,
                'phone' => '081901234567',
                'email' => null,
                'website' => null,
                'operating_hours' => '07:00 - 17:00 WIB',
                'products' => 'Meja, kursi, lemari, pintu, jendela, rak buku',
                'services' => 'Desain furniture, renovasi rumah, perbaikan furniture',
                'price_range' => 'Rp 100.000 - Rp 2.000.000',
                'employee_count' => 5,
                'monthly_revenue' => 16500000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=250&fit=crop']),
                'rating' => 4.7,
                'total_reviews' => 24,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(12),
            ],
            [
                'business_name' => 'Laundry Express',
                'slug' => 'laundry-express',
                'owner_name' => 'Ibu Dewi Sartika',
                'category' => 'jasa',
                'description' => 'Layanan laundry kiloan dan satuan dengan sistem pickup dan delivery.',
                'address' => 'Dusun III RT 03/RW 03',
                'settlement_id' => $settlements->random()->id,
                'phone' => '082012345678',
                'email' => 'laundry.express.krandegan@gmail.com',
                'website' => null,
                'operating_hours' => '08:00 - 20:00 WIB',
                'products' => null,
                'services' => 'Cuci kiloan, cuci kering, setrika, pickup delivery',
                'price_range' => 'Rp 4.000 - Rp 15.000/kg',
                'employee_count' => 4,
                'monthly_revenue' => 11500000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400&h=250&fit=crop']),
                'rating' => 4.1,
                'total_reviews' => 67,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(5),
            ],
            [
                'business_name' => 'Budidaya Lele Makmur',
                'slug' => 'budidaya-lele-makmur',
                'owner_name' => 'Bapak Wahyu Nugroho',
                'category' => 'pertanian',
                'description' => 'Budidaya ikan lele dengan sistem bioflok dan pakan organik.',
                'address' => 'Dusun II RT 02/RW 02',
                'settlement_id' => $settlements->random()->id,
                'phone' => '082123456789',
                'email' => null,
                'website' => null,
                'operating_hours' => '06:00 - 18:00 WIB',
                'products' => 'Ikan lele segar, bibit lele, pakan ikan',
                'services' => 'Konsultasi budidaya, pelatihan bioflok',
                'price_range' => 'Rp 18.000 - Rp 22.000/kg',
                'employee_count' => 3,
                'monthly_revenue' => 13500000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=250&fit=crop']),
                'rating' => 4.0,
                'total_reviews' => 19,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(9),
            ],
            [
                'business_name' => 'Salon Cantik Permata',
                'slug' => 'salon-cantik-permata',
                'owner_name' => 'Ibu Sari Indah',
                'category' => 'jasa',
                'description' => 'Salon kecantikan lengkap dengan perawatan wajah dan rambut profesional.',
                'address' => 'Dusun I RT 03/RW 01',
                'settlement_id' => $settlements->random()->id,
                'phone' => '082234567890',
                'email' => null,
                'website' => null,
                'operating_hours' => '09:00 - 19:00 WIB',
                'products' => null,
                'services' => 'Potong rambut, creambath, facial, manicure, pedicure',
                'price_range' => 'Rp 15.000 - Rp 75.000',
                'employee_count' => 3,
                'monthly_revenue' => 8500000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=250&fit=crop']),
                'rating' => 4.5,
                'total_reviews' => 34,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(11),
            ],
            [
                'business_name' => 'Catering Nusantara',
                'slug' => 'catering-nusantara',
                'owner_name' => 'Ibu Fatimah',
                'category' => 'makanan',
                'description' => 'Jasa catering untuk berbagai acara dengan menu nusantara yang lezat.',
                'address' => 'Dusun III RT 04/RW 03',
                'settlement_id' => $settlements->random()->id,
                'phone' => '082345678901',
                'email' => 'catering.nusantara@gmail.com',
                'website' => null,
                'operating_hours' => 'By Appointment',
                'products' => null,
                'services' => 'Catering pernikahan, arisan, acara kantor, aqiqah',
                'price_range' => 'Rp 12.000 - Rp 25.000/porsi',
                'employee_count' => 7,
                'monthly_revenue' => 19000000,
                'logo_path' => null,
                'photos' => json_encode(['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=250&fit=crop']),
                'rating' => 4.8,
                'total_reviews' => 29,
                'is_active' => true,
                'is_verified' => true,
                'registered_at' => now()->subMonths(14),
            ],
        ];

        foreach ($umkmData as $data) {
            Umkm::create($data);
        }
    }
}
